config/routes.rb
Rails.application.routes.draw do

  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'
  resources :plan, only: [:index]
  get 'welcome/index'
  root 'welcome#index'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,	:validate => true
  attribute :nickname,  :captcha  => true

  def headers 
  	{
  	:subject => 'contact Form',
  	:to => 'kilokingw@gmail.com',
  	:form => %("#{name}" <#{email})
  	}
  	
  end

end

app/models/message.rb
class Message

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :content,
    presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = '無法傳送訊息'
			render :new
		end	
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def new
    	@message = Message.new
  end

	def create
	    @message = Message.new(message_params)
	    
	    if @message.valid?
	      MessageMailer.new_message(@message).deliver
	      redirect_to root_path, notice: "謝謝，您的訊息已經送出，將盡快回覆您。"
	    else
	      redirect_to root_path, notice: "訊息傳送失敗，請嘗試再填寫一次。"
	    end
	end

	private

	def message_params
	    params.require(:message).permit(:name, :email, :content)
	end
end

app/controllers/plan_controller.rb
class PlanController < ApplicationController
	def index
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_post, only: [:show, :edit , :update , :destroy]

	def index
		
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: '歡迎'
		else
			render 'new' , notice: '出錯了'
		end	
	end

	def show

		
	end

	def edit
			
	end	



	def update
		if @post.update post_params
			redirect_to @post, notice: '更新了'
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private


	def post_params
		params.require(:post).permit(:title, :content)
	end

	def find_post
		@post = Post.find(params[:id])
		
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/plan_helper.rb
module PlanHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
	<div class="skinny_wrapper wrapper_padding">
		<h1>感謝您的來信！</h1>
		<p>我們將會盡快回覆您</p>	
	</div>

app/views/contacts/new.html.erb
<h1>Hello</h1>

	<div class="skinny_wrapper wrapper_padding">
		<%= form_for @contact do |f| %>	
			<%= f.label :name %> <br>
			<%= f.text_field :name, required: true %>

			<br>

			<%= f.label :email %> <br>
			<%= f.email_field :email, required: true %>

			<br>

			<%= f.label :message %> <br>
			<%= f.text_area :message, as: :text %>

			<div class="hidden">
				<%= f.label :nickname %> <br>
				<%= f.text_field :nickname, hint: 'leaves this field blank' %>
			</div>

			<%= f.submit 'Send Message', class: 'button' %>
		<% end %>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
	<title>成家居 - mobile first 複合式網頁設計服務，手機、平板、桌機瀏覽率一網打盡</title>
	<link rel="stylesheet" href="css/application.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	<script type="text/javascript" src="js/jquery-1.11.3.min.js" ></script>
	<script type="text/javascript" src="js/jquery.easing.min.js"></script>
	<script type="text/javascript" src="js/jquery.easy-ticker.js"></script>
	<script type="text/javascript" src="js/main.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70748785-1', 'auto');
  ga('send', 'pageview');

</script>
</head>

<script type="text/javascript">
$(document).ready(function(){

	var dd = $('.vticker').easyTicker({
		direction: 'up',
		easing: 'easeInOutBack',
		speed: 'slow',
		interval: 2000,
		height: 'auto',
		visible: 1,
		mousePause: 0,
		controls: {
			up: '.up',
			down: '.down',
			toggle: '.toggle',
			stopText: 'Stop !!!'
		}
	}).data('easyTicker');
	
	cc = 1;
	$('.aa').click(function(){
		$('.vticker ul').append('<li>' + cc + ' Triangles can be made easily using CSS also without any images. This trick requires only div tags and some</li>');
		cc++;
	});
	
	$('.vis').click(function(){
		dd.options['visible'] = 3;
		
	});
	
	$('.visall').click(function(){
		dd.stop();
		dd.options['visible'] = 0 ;
		dd.start();
	});
	
});
</script>
<body>
	<div id="gotop">˄</div>
	<header id="main_navigation" class="clearfix"> 
		<a href="/" class="name">成家居</a>
		<div class="soical"> <a href="tel:0982826405">聯絡電話 : 0982826405(小吳)</a> | <a href="http://line.me/ti/p/a1jsBe9PCj"><%= image_tag('line.png', height: '20', width: '20') %>Line : wuwood</a> | <a href="mailto:threemouth@threemouth.com">threemouth@threemouth.com</a> </div>
		<nav>
			<%= link_to '網誌' , root_path %>
				
			<a href="#" id="ct">方案與費用</a>
			<a href="#" id="dt">聯絡我們</a>
			
			<%= link_to '地產企劃' , plan_index_path , class: 'special' %>
		</nav>			
	</header>
<%= yield %>
	<footer id="main_footer">
		<p class="copyright">&copy; 2015 參口創意網路團隊 版權所有 </p>
		<nav>
			<a href="tel:0982826405" target="_blank"><i class="fa fa-phone-square"></i></a>
			<a href="https://www.facebook.com/threemouth/" target="_blank"><i class="fa fa-facebook-official"></i></a>
			<a href="mailto:threemouth@threemouth.com" target="_blank"><i class="fa fa-envelope"></i></a>
			<a href="https://github.com/kiloking" target="_blank"><i class="fa fa-github"></i></a>
		</nav>	
	</footer>	


</body>
</html>

app/views/messages/new.html.erb
<div class="skinny_wrapper wrapper_padding">
<%= form_for @message, url: contact_path do |message_form| %>
  
      <%= message_form.label :name %> <br>
      <%= message_form.text_field :name, placeholder: "尊姓大名"%>
    
      <br>
      <%= message_form.label :email %> <br>
      <%= message_form.email_field :email, placeholder: "輸入電子信箱"%>
      <br>
    
      <%= message_form.label :content %> <br>
      <%= message_form.text_area :content, placeholder: "請輸入訊息及聯絡電話"%>
    
  
      <br>
  
      <%= message_form.submit 'Send Message', class: 'button' %>
    
  
<% end %>
</div>

app/views/plan/index.html.erb
<div class="wrapper clearfix ">

		<div class="likesfb">
			<h4>房地產企劃:墨非</h4>
			
			
		</div>	
	</div>	

app/views/posts/_form.html.erb
<%=  form_for @post do |f| %>
	<% if @post.errors.any? %>
	<h2><%= pluralize(@post.errors.count, 'error') %> prevented this post form saving:</h2>
	<ul>
		<%= @post.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
	<% end %>

	<%= f.label :title %>
	<%= f.text_field :title %>

	<br>
	<br>

	<%= f.label :content, '寫上文字' %>
	<%= f.text_area :content %>

	<br>
	<br>

	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>編輯</h1>

<%=  render 'form' %>	

app/views/posts/index.html.erb
<h1>hihihi</h1>

app/views/posts/new.html.erb
<h1>new post</h1>

<%=  render 'form' %>	

app/views/posts/show.html.erb
<%= @post.title %>
<%= @post.content %>

<br>
<br>
<%= link_to 'Edit' , edit_post_path(@post) %>
<%= link_to 'del' , post_path(@post), method: :delete, data:{ confirm: '要刪除嗎'} %>

app/views/welcome/index.html.erb
<%=  flash[:notice] %>
<div class="wrapper clearfix banner">
		<div class="banner-1 slideshow autoPlay">
			<ul>
				<li>
					<a href="#">
					<%= image_tag('area01/banner01.jpg') %>
					<span class="mask-tags" data-type="sports">2015/11</span>
					</a>
				</li>
				<li>
					<a href="#">
					<%= image_tag('area01/banner01-2.jpg') %>
					<span class="mask-tags" data-type="sports">最新 2015/05</span>
					</a>
				</li>
				<li>
					<a href="#">
					<%= image_tag('area01/banner01-3.jpg') %>
					<span class="mask-tags" data-type="sports">最新 2015/11</span>
					</a>
				</li>
				<li>
					<a href="#">
					<%= image_tag('area01/banner01-2.jpg') %>
					<span class="mask-tags" data-type="sports">最新 2015/02</span>
					</a>
				</li>
				<li>
					<a href="#">
					<%= image_tag('area01/banner01-3.jpg') %>
					<span class="mask-tags" data-type="sports">最新 2015/11</span>
					</a>
				</li>
			</ul>
				
		</div>
		<div class="small-images">
			<div class="banner-2 block wider slideshow">
				<ul>
					<li>
						<a href="#">
						<%= image_tag('area02/banner02.jpg') %>
						<span class="mask-tags" data-type="sports">龍潭 大樓</span>
						</a>
					</li>
					<li>
						<a href="#">
						<%= image_tag('area02/banner02.jpg') %>
						<span class="mask-tags" data-type="sports">大樓</span>
						</a>
					</li>
					<li>
						<a href="#">
						<%= image_tag('area02/banner02.jpg') %>
						<span class="mask-tags" data-type="sports">大樓</span>
						</a>
					</li>
				</ul>
				
			</div>
			<div class="banner-2 block ad slideshow">
				
					<ul>
						<li>
							<a href="#">
								<%= image_tag('area03/banner03.jpg') %>
								<span class="mask-tags" data-type="sports">桃園 大樓</span>
							</a>
						</li>
						<li>
							<a href="#">
								<%= image_tag('area03/banner03.jpg') %>
								<span class="mask-tags" data-type="sports">大樓</span>
							</a>
						</li>	
						<li>
							<a href="#">
								<%= image_tag('area03/banner03.jpg') %>
								<span class="mask-tags" data-type="sports">大樓</span>
							</a>				
						</li>
					</ul>
					
			</div>
			<div class="banner-2 block ad slideshow">
				<ul>
					<li>
						<a href="#">
							<%= image_tag('area04/banner04.jpg') %>
							<span class="mask-tags" data-type="sports">青埔 大樓</span>
						</a>
					</li>
					<li>
						<a href="#">
							<%= image_tag('area04/banner04.jpg') %>
							<span class="mask-tags" data-type="sports">大樓</span>
						</a>
				</li>
				</ul>
			</div>
			<div class="banner-2 block ad slideshow">
				<ul>
					<li>
						<a href="#">
							<%= image_tag('area05/banner05.jpg') %>
							<span class="mask-tags" data-type="sports">最新企劃 2015/12</span>
						</a>
					</li>
					<li>
						<a href="#">
							<%= image_tag('area05/banner05.jpg') %>
							<span class="mask-tags" data-type="sports">最新企劃 2015/12</span>
						</a>
					</li>
					<li>
						<a href="#">
							<%= image_tag('area05/banner05.jpg') %>
							<span class="mask-tags" data-type="sports">最新企劃 2015/12</span>
						</a>
					</li>

				</ul>
				
			</div>



		</div>
		
	</div>	
	<div class="wrapper clearfix ">
		<div class="quicknews vticker">
			<ul>
				<li><a href="">1桃園 青埔 宜誠國塘 現正熱銷上線。</a></li>
				<li><a href="">2桃園 青埔 宜誠國塘 現正熱銷上線。</a></li>
				<li><a href="">3桃園 青埔 宜誠國塘 現正熱銷上線。</a></li>
				<li><a href="">4桃園 青埔 宜誠國塘 現正熱銷上線。</a></li>
				<li><a href="">5桃園 青埔 宜誠國塘 現正熱銷上線。</a></li>
			</ul>
			
		</div>
	</div>
	<div class="wrapper clearfix ">
		<div class="adhere">
		<%=  image_tag('gg.jpg')%>

		</div>	
		<div class="likesfb">
			<h4>我們的服務，毫不囉唆</h4>
			
			<p>以瀏覽速度為優先，進化你的網站，手機、平板、桌機一次搞定。</p>
			<p>Google已經重新定義網站</p>
			<p>成長 = 機會 ; 限制 = 專注 ; 潛力 = 創新</p>
			
			<%= image_tag('alldevices.png')  %>

			<div class="arrow"><a href="#two"><i class="fa fa-arrow-down"></i></a></div>
		</div>	
	</div>	
	<div class="fullbar" >
			<p>不只趕流行，我們要讓你走在時代的尖端。</p>
			<p>引文: <a href="http://www.inside.com.tw/2010/11/13/mobile-first" target="_blank">頂尖公司都在喊：手機優先（Mobile First！），您呢？</a></p>
	</div>	
	<h1 class="page-title">方案與費用</h1>
	<h4 class="second-title" id="price">靈活且親切的服務方案，供您選擇。</h4>

	<div class="wrapper clearfix wrapper_padding " >

		 <div class="price-1">
		 	<ul>
		 		<li class="price-name-1">基礎制式方案 <span class="ps">個案適用</span></li>
		 		<li class="price-old-1">定價：40000元/年</li>
		 		<li class="price-new-1">優惠價：25200元/年</li>
		 		<li>六大單元頁面</li>
		 		<li>固定專用版型 <a href="http://threemouth.com/kuotown/" target="_blank">參考</a></li>
		 		<li>3~5天快速上線</li>
		 		<li>免年維護費、免費推廣</li>


		 		<li class="last">
		 			<a href="tel:0982826405"><div class="callmenow"><i class="fa fa-phone"></i></div></a>
		 			<a href="mailto:threemouth@threemouth.com"><div class="callmenow"><i class="fa fa-envelope"></i></div></a>
		 			<a href="http://line.me/ti/p/a1jsBe9PCj"><div class="callmenow"><%= image_tag('line.png') %></div></a>
		 		</li>
		 	</ul>	
		 </div>
		 <div class="price-1">
		 	<ul>
		 		<li class="price-name-1 price-name-2">客製RWD方案 <span class="ps">個案適用</span></li>
		 		<li class="price-old-1">定價：80,000元</li>
		 		<li class="price-new-1">50,000元起</li>
		 		<li>彈性單元頁面數:依企劃架構</li>
		 		<li>另製版型</li>
		 		<li>專人溝通需求</li>
		 		<li>年維護費8,000~12,000元</li>


		 		<li class="last">
		 			<a href="tel:0982826405"><div class="callmenow"><i class="fa fa-phone"></i></div></a>
		 			<a href="mailto:threemouth@threemouth.com"><div class="callmenow"><i class="fa fa-envelope"></i></div></a>
		 			<a href="http://line.me/ti/p/a1jsBe9PCj"><div class="callmenow"><%= image_tag('line.png') %></div></a>
		 		</li>
		 	</ul>	
		 </div>
		 <div class="clearfix"></div>
		 <div class="talk">
		 <ul>
		 		
		 		<li>官網平台廣告優先</li>
		 		<li>行動裝置瀏覽整合</li>
		 		<li>整合電子信箱</li>
		 		<li>整合聯絡電話</li>
		 		<li>整合lineID</li>
		 		<li>整合FB粉絲團</li>
		 		<li>GA流量分析</li>
		 		<li>搜尋引擎登錄</li>
		 		<li>掛載高流量空間</li>
		 		<li>附屬名稱網址</li>
		 </ul>

		</div>
		 
	</div>

	<h1 class="page-title" id="contact">聯絡我們</h1>
	<h4 class="second-title">網站客製？ 預算？ 大型專案處理？ 關鍵字？ 手機版？ 需要專人解說嗎？ 歡迎來信！</h4>
	
	<div class="skinny_wrapper wrapper_padding">
	<%= form_for Message.new, url: contact_path do |message_form| %>
  
      <%= message_form.label :name %> <br>
      <%= message_form.text_field :name, placeholder: "尊姓大名"%>
    
      <br>
      <%= message_form.label :email %> <br>
      <%= message_form.email_field :email, placeholder: "輸入電子信箱"%>
      <br>
    
      <%= message_form.label '訊息內容' %> <br>
      <%= message_form.text_area :content, placeholder: "請輸入訊息及聯絡電話"%>
    
  
      <br>
  
      <%= message_form.submit 'Send Message', class: 'button' %>
    
  
	<% end %>
	</div>